# Generated by Django 4.2.13 on 2024-06-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clienteCompetitivo',
            fields=[
                ('id_competitivo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_competitivo', models.CharField(default='John', max_length=30)),
                ('apellido_competitivo', models.CharField(default='Doe', max_length=30)),
                ('rut_competitivo', models.IntegerField()),
                ('plan_competitivo', models.CharField(max_length=20)),
                ('vueltas_disponibles', models.IntegerField(default=0)),
                ('fechaRegistro_competitivo', models.DateField()),
                ('estado_competitivo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='kart',
            fields=[
                ('id_kart', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_kart', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('password_usuario', models.CharField(max_length=20)),
                ('rol_usuario', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tablaClasificacion',
            fields=[
                ('id_tablaClasificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_clienteCompetitivo', models.CharField(default='John', max_length=30)),
                ('apellido_clienteCompetitivo', models.CharField(default='Doe', max_length=30)),
                ('tiempoVueltaMasRapida', models.TimeField()),
                ('id_competitivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sskapp.clientecompetitivo')),
            ],
        ),
        migrations.AddField(
            model_name='clientecompetitivo',
            name='id_kart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sskapp.kart'),
        ),
        migrations.AddField(
            model_name='clientecompetitivo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sskapp.usuario'),
        ),
        migrations.CreateModel(
            name='clienteCasual',
            fields=[
                ('id_casual', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_casual', models.CharField(default='John', max_length=30)),
                ('apellidoCasual', models.CharField(default='Doe', max_length=30)),
                ('rut_casual', models.IntegerField()),
                ('plan_casual', models.CharField(max_length=20)),
                ('tiempo_disponible', models.TimeField()),
                ('fechaRegistro_casual', models.DateField()),
                ('estado_casual', models.CharField(max_length=30)),
                ('id_kart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sskapp.kart')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sskapp.usuario')),
            ],
        ),
    ]
