# Generated by Django 4.2.13 on 2024-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecasual',
            name='id_casual',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientecompetitivo',
            name='id_competitivo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tablaclasificacion',
            name='id_tablaClasificacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
